name: Build

on:
  push:
    branches: '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
    - name: Build
      run:  dotnet build "AppsApi.csproj" -c Debug
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AppsApi
        path: bin/Debug/net8.0
